### ISSUE TITLE
Por que a outra classificação de DNA é "Sigmano"?

### ISSUE THREAD

**Issue by Birlinha** [RebecaSSilva/Sigmano-detector#1]
Fiquei na dúvida sobre o que é um Sigmano e porque a escolha dessa palavra :p

Mas eu gostei muito da aplicação!!!
O layout ta foda demais, o conceito é bão e tem até registro! Gostei
Achei muito bom o uso do environment pra conter o ambiente do código e manter a reproducibilidade!! Mandou muito

**Comment by RebecaSSilva** [comment]
Na verdade é um desafio que foi proposto, a origem do nome não foi criação minha mas  o código sim hehe.
Fico feliz que tenha gostado! 
Obrigadaa :D

**Comment by Birlinha** [comment]
De nada!! 
Bons estudos! :D
